"""Shape of ``tests/fixtures/models_v1_reference.json``, the frozen v1 wire-template truth.

The fixture holds the handler's recorded recipe (``cmd``, ``subCmd``, ``params``) for every
payload of every v1 wire-template entry, per device context, plus the hardware-proven rows.
It is generated by a private freeze tool and never edited by hand. This module reads it as
plain data and imports no library module.
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest

FIXTURE = Path(__file__).resolve().parents[1] / "fixtures" / "models_v1_reference.json"
MODELS = frozenset({"T8030", "T8160", "T8170", "T8910"})
SERIAL = re.compile(r"T[0-9A-Z]{4}[A-Z0-9]{11}")
SERIAL_SLOTS = frozenset({"$device_sn", "$station_sn"})
RECIPE_KEYS = frozenset({"cmd", "subCmd", "params"})


@pytest.fixture(scope="module")
def text() -> str:
    return FIXTURE.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def doc(text: str) -> dict[str, Any]:
    loaded: dict[str, Any] = json.loads(text)
    return loaded


def _strings(node: object) -> Iterator[str]:
    if isinstance(node, str):
        yield node
    elif isinstance(node, dict):
        for key, value in node.items():
            yield key
            yield from _strings(value)
    elif isinstance(node, list):
        for value in node:
            yield from _strings(value)


def _entry_rows(doc: dict[str, Any], code: str, identifier: str) -> list[dict[str, Any]]:
    return [r for r in doc["rows"] if (r["product_code"], r["identifier"]) == (code, identifier)]


def test_counts(doc: dict[str, Any]) -> None:
    assert doc["format"] == 1
    entries = {(r["product_code"], r["identifier"]) for r in doc["rows"]}
    assert len(entries) == 34
    assert {code for code, _ in entries} == MODELS
    assert len(doc["rows"]) == 136


def test_row_shape(doc: dict[str, Any]) -> None:
    for row in doc["rows"]:
        assert row["context"] in {"child", "standalone"}, row
        assert type(row["channel"]) is int, row
        recipe = row["recipe"]
        assert set(recipe) <= RECIPE_KEYS, row
        assert type(recipe["cmd"]) is int, row
        assert "subCmd" not in recipe or type(recipe["subCmd"]) is int, row
        assert isinstance(recipe["params"], dict), row


def test_hardware_items_match_their_rows(doc: dict[str, Any]) -> None:
    assert len(doc["hardware"]) == 9
    for item in doc["hardware"]:
        rows = _entry_rows(doc, item["product_code"], item["identifier"])
        assert rows, item
        payloads = {json.dumps(r["payload"]) for r in rows}
        assert item["payloads"], item
        assert {json.dumps(p) for p in item["payloads"]} <= payloads, item
        for row in rows:
            recipe = row["recipe"]
            assert item["command_id"] == recipe.get("subCmd", recipe["cmd"]), item


def test_no_serials(doc: dict[str, Any]) -> None:
    for value in _strings({"rows": doc["rows"], "hardware": doc["hardware"]}):
        assert not SERIAL.search(value), value
        assert not value.startswith("$") or value in SERIAL_SLOTS, value


def test_canonical_bytes(text: str) -> None:
    assert json.dumps(json.loads(text), indent=1, sort_keys=True) + "\n" == text
