"""Generate ``src/eufy_home_security/devices/app_models.py`` from the eufy app's model tables.

Three source files of the eufy Security app (build ``--app-version``) name the
products: the model constants (one ``String`` constant per serial prefix, e.g.
``CAMERA2C = "T8113"``), the device-type map (``hashMap.put(<type>, new
String[]{<prefixes>})``) and the device-type ints (the ``TYPE_*`` ints that map refers to
by name). The output lists, per five-character prefix: the app's constant name, the device
kind read from that name (:data:`KIND_RULES`) and the cloud ``device_type`` when the map
gives one. A prefix whose constants read as different kinds is left out and reported.
``--check`` compares with the committed module.

Runs on a maintainer host (the app's code is not shipped):

    gen_app_models.py --constants FILE --type-map FILE --device-types FILE
                      --app-version V [--out FILE] [--check] [--allow-shrink]

It refuses (exit 1, nothing written) when the inputs give no rows, or fewer than
:data:`SHRINK_MARGIN` of the rows ``--out`` holds unless ``--allow-shrink``.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = ROOT / "src" / "eufy_home_security" / "devices" / "app_models.py"
#: The share of ``--out``'s rows a run must keep without ``--allow-shrink``.
SHRINK_MARGIN = 0.9
PREFIX = re.compile(r"T[0-9A-Z]{4}")

_CONSTANT = re.compile(r'public static final String ([A-Z0-9_]+) = "([^"]*)";')
_ROW = re.compile(r'^    \("', re.MULTILINE)
_TYPE_INT = re.compile(r"public static final int (TYPE_[A-Za-z0-9_]+) = (\d+);")
_TYPE_PUT = re.compile(
    r"hashMap\.put\((?:Integer\.valueOf\()?(?:[A-Za-z]\w*\.)?([A-Za-z0-9_]+)\)?, "
    r"new String\[\]\{([^}]*)\}\);"
)

#: Kind by the words of the app's constant name, first match wins. A siren accessory
#: (``SIREN_SENSOR``) is no sensor: it sounds, it does not trigger.
KIND_RULES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("other", ("SIREN",)),
    ("station", ("STATION",)),
    ("keypad", ("KEYPAD",)),
    ("lock", ("LOCK",)),
    ("doorbell", ("DOORBELL",)),
    ("sensor", ("SENSOR",)),
    ("camera", ("CAM", "CAMERA", "DOGCAM", "FLOODLIGHT", "FLOODLIGHT2", "WALLLIGHT")),
)
OTHER = "other"


def kind_of(constant: str) -> str:
    """The device kind a constant's name reads as (:data:`KIND_RULES`), else ``other``."""
    words = set(constant.split("_"))
    words |= {w.rstrip("0123456789") for w in words}  # CAMERA2C → CAMERA, CAMERA3 → CAMERA
    words |= {re.sub(r"\d.*$", "", w) for w in words}
    for kind, markers in KIND_RULES:
        if words & set(markers):
            return kind
    return OTHER


def constants(text: str) -> dict[str, list[str]]:
    """Each five-character prefix with the constant names that hold it, in file order."""
    found: dict[str, list[str]] = {}
    for name, value in _CONSTANT.findall(text):
        if PREFIX.fullmatch(value):
            found.setdefault(value, []).append(name)
    return found


def device_types(type_map: str, type_ints: str) -> dict[str, int]:
    """Each prefix the device-type map names, with its type; a name the ints do not define
    is skipped. A prefix named under two types raises ``ValueError``."""
    ints = {name: int(value) for name, value in _TYPE_INT.findall(type_ints)}
    out: dict[str, int] = {}
    for key, listed in _TYPE_PUT.findall(type_map):
        number = int(key) if key.isdigit() else ints.get(key)
        if number is None:
            continue
        for prefix in re.findall(r'"([^"]+)"', listed):
            if not PREFIX.fullmatch(prefix):
                continue
            if prefix in out and out[prefix] != number:
                raise ValueError(f"{prefix} is mapped to device types {out[prefix]} and {number}")
            out[prefix] = number
    return out


def build(
    named: dict[str, list[str]], types: dict[str, int]
) -> tuple[list[tuple[str, str, str, int | None]], list[str]]:
    """The rows ``(prefix, constant, kind, device_type)`` sorted by prefix, and the
    prefixes left out because their constants read as different kinds."""
    rows: list[tuple[str, str, str, int | None]] = []
    conflicts: list[str] = []
    for prefix in sorted(named):
        names = named[prefix]
        kinds = {kind_of(n) for n in names}
        if len(kinds) > 1:
            conflicts.append(f"{prefix}: {', '.join(f'{n} ({kind_of(n)})' for n in names)}")
            continue
        rows.append((prefix, min(names, key=len), kinds.pop(), types.get(prefix)))
    return rows, conflicts


def render(rows: list[tuple[str, str, str, int | None]], app_version: str) -> str:
    """The generated module's text."""
    lines = [
        f'"""Product models of the eufy Security app {app_version}: generated by',
        "``scripts/gen_app_models.py``, do not edit.",
        "",
        "Per serial prefix: the app's model constant name, the device kind that name reads",
        "as, and the cloud ``device_type`` from the app's device-type map (None where it",
        'gives none)."""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Final",
        "",
        f'APP_VERSION: Final = "{app_version}"',
        "",
        "APP_MODELS: Final[tuple[tuple[str, str, str, int | None], ...]] = (",
    ]
    lines += [f'    ("{p}", "{c}", "{k}", {t}),' for p, c, k, t in rows]
    lines += [")", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").split("\n\n")[0])
    parser.add_argument(
        "--constants", type=Path, required=True, help="the app's model constants file"
    )
    parser.add_argument(
        "--type-map", type=Path, required=True, help="the app's device-type map file"
    )
    parser.add_argument(
        "--device-types", type=Path, required=True, help="the app's device-type ints file"
    )
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--app-version", required=True, help="the app build the inputs are from")
    parser.add_argument("--check", action="store_true", help="compare with --out, write nothing")
    parser.add_argument(
        "--allow-shrink", action="store_true", help="write even when rows drop beyond the margin"
    )
    args = parser.parse_args(argv)
    sources = (args.constants, args.type_map, args.device_types)
    missing = [str(p) for p in sources if not p.is_file()]
    if missing:
        print(f"missing input: {', '.join(missing)}", file=sys.stderr)
        return 2
    named = constants(args.constants.read_text(encoding="utf-8"))
    types = device_types(
        args.type_map.read_text(encoding="utf-8"), args.device_types.read_text(encoding="utf-8")
    )
    rows, conflicts = build(named, types)
    for line in conflicts:
        print(f"left out, kinds differ: {line}", file=sys.stderr)
    if not rows:
        print("no models in the inputs; nothing written", file=sys.stderr)
        return 1
    before = len(_ROW.findall(args.out.read_text(encoding="utf-8"))) if args.out.is_file() else 0
    if len(rows) < before * SHRINK_MARGIN and not args.allow_shrink:
        print(
            f"{len(rows)} models against {before} in {args.out}; nothing written "
            "(--allow-shrink to write)",
            file=sys.stderr,
        )
        return 1
    text = render(rows, args.app_version)
    if args.check:
        same = args.out.is_file() and args.out.read_text(encoding="utf-8") == text
        print("check: up to date" if same else f"check: {args.out} differs")
        return 0 if same else 1
    args.out.write_text(text, encoding="utf-8")
    print(f"{len(rows)} models written to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
