"""Render the device support matrix as Markdown, from the device catalog and the
bundled per-model settings files."""

from __future__ import annotations

from collections.abc import Iterable, Sequence

from .capabilities import GUARD_MODE_EVIDENCE, PROFILES, Capability
from .model_settings import Setting, SettingKind, Value, bundled_codes, settings_of
from .support import Evidence, Support
from .types import MODELS

_LEGEND = {
    Support.VERIFIED: "proven on real hardware (a live capture, or a live write plus read-back)",
    Support.DECLARED: "present in the app's own code or enums, not yet proven on hardware",
    Support.UNKNOWN: "seen but not understood, or known not to work",
}


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _table(header: Sequence[str], rows: Iterable[Sequence[str]]) -> list[str]:
    lines = [
        "| " + " | ".join(header) + " |",
        "|" + "|".join("---" for _ in header) + "|",
    ]
    lines.extend("| " + " | ".join(_cell(c) for c in row) + " |" for row in rows)
    return lines


def _source(evidence: Evidence) -> str:
    return f"{evidence.source} ({evidence.note})" if evidence.note else evidence.source


def _value(value: Value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _domain(setting: Setting) -> str:
    """Enum values, flags members, or ``min..max step s`` for a range; ``-`` otherwise."""
    if setting.kind is SettingKind.FLAGS:
        return "any of " + ", ".join(setting.flags)
    if setting.kind is SettingKind.ENUM and setting.values:
        return ", ".join(_value(v) for v in setting.values)
    if setting.minimum is not None and setting.maximum is not None:
        step = "" if setting.step is None else f" step {_value(setting.step)}"
        return f"{_value(setting.minimum)}..{_value(setting.maximum)}{step}"
    return "-"


def _settings_counts(code: str) -> tuple[int, int]:
    """(writable, read-only) settings of ``code``'s settings file."""
    settings = settings_of(code).values()
    writable = sum(1 for s in settings if s.writable)
    return writable, len(settings) - writable


def _settings_title(code: str) -> str:
    model = MODELS.get(code)
    return f"Settings of {code} {model.name}" if model is not None else f"Settings of {code}"


def _anchor(title: str) -> str:
    """The Markdown heading anchor of ``title``."""
    kept = "".join(c for c in title.lower() if c.isalnum() or c in " -_")
    return kept.replace(" ", "-")


def _settings_section(code: str) -> list[str]:
    """One model's settings file: heading, ``rw N / ro M`` and a row per setting by key."""
    settings = settings_of(code)
    rw, ro = _settings_counts(code)
    out = ["", f"### {_settings_title(code)}", "", f"rw {rw} / ro {ro}", ""]
    out += _table(
        ("key", "kind", "values or range", "unit", "writable", "control", "labels"),
        (
            (
                f"`{s.key}`",
                s.kind.value,
                _domain(s),
                s.unit.value if s.unit is not None else "-",
                "yes" if s.writable else "no",
                s.control.value if s.control is not None else "-",
                ", ".join(f"{_value(v)}={title}" for v, title in s.labels.items()) or "-",
            )
            for _, s in sorted(settings.items())
        ),
    )
    return out


def render_support_matrix() -> str:
    """The whole support matrix, deterministically ordered."""
    out = [
        "# Device support matrix",
        "",
        "<!-- Generated by scripts/gen_device_matrix.py from eufy_home_security.devices;"
        " do not edit. -->",
        "",
        "Support legend (models, capabilities and guard modes):",
        "",
    ]
    out.extend(f"- **{status}**: {meaning}" for status, meaning in _LEGEND.items())
    out += ["", "## Models", ""]
    out += _table(
        ("model", "name", "kind", "cloud device_type", "support", "source"),
        (
            (
                m.model,
                m.name,
                m.kind,
                "" if m.cloud_device_type is None else str(m.cloud_device_type),
                m.evidence.support,
                _source(m.evidence),
            )
            for m in sorted(MODELS.values(), key=lambda m: m.model)
        ),
    )
    out.append("")
    out.append("Models without a profile below offer no capability (all *unknown*).")
    for model in sorted(PROFILES):
        profile = PROFILES[model]
        out += ["", f"## {model} {MODELS[model].name}", ""]
        out += _table(
            ("capability", "support", "source"),
            (
                (cap, profile.capabilities[cap].support, _source(profile.capabilities[cap]))
                for cap in Capability
                if cap in profile.capabilities
            ),
        )
        rw, ro = _settings_counts(model)
        out += [
            "",
            f"Settings: rw {rw} / ro {ro}, see [{_settings_title(model)}](#{_anchor(_settings_title(model))})",
            "",
        ]
        if profile.kind_markers:
            markers = ", ".join(str(pid) for pid in sorted(profile.kind_markers))
            out += [f"Kind markers (a block without a known serial): {markers}", ""]
        out += _table(
            ("parameter", "id"),
            ((name, str(pid)) for name, pid in sorted(profile.params.items())),
        )
    out += ["", "## Guard modes", ""]
    out += _table(
        ("mode", "code", "support", "source"),
        (
            (mode.name.lower(), str(int(mode)), evidence.support, _source(evidence))
            for mode, evidence in sorted(GUARD_MODE_EVIDENCE.items())
        ),
    )
    out += ["", "Modes not listed carry no recorded evidence."]
    out += [
        "",
        "## Settings",
        "",
        "Each model's settings as its bundled settings file lists them: *rw* settings the "
        "library can write, *ro* settings it only reads or lists. *control* is the control "
        "a UI offers for a writable setting. *labels* are the app's titles of the values.",
        "",
        "The per-mode settings (`alarm_delay_<mode>`, `leaving_delay_<mode>` and "
        "`<scope>_action_<mode>`) are not model data: they apply to every camera and "
        "sensor paired to a station and are listed with that device's settings.",
    ]
    for code in bundled_codes():
        out += _settings_section(code)
    out.append("")
    return "\n".join(out)
